#!/usr/bin/env python
# Copyright (C) <2020> PMBL;South China Agricultural University. All rights reserved
__author__ = "Write by Fangping Li"
__version__ = '0.1.0'

import argparse
import sys
import os
def get_options():
    description = "Create lineal pangenome"
    parser = argparse.ArgumentParser(description = description,prog = 'creatpangenome.py')
    parser.add_argument('--version', action='version',version='%(prog)s '+__version__+" "+__author__)  
    parser.add_argument('-1', '--reference', action='store',type=str,help='input your reference .fasta')
    parser.add_argument('-2', '--query', action='store',type=str,help='input your query .fasta')    
    parser.add_argument('-g', '--svguide', action='store',type=str,help='input your sv file generated by svmu')
    parser.add_argument('-o', '--output', action='store',type=str,help='name of the  pan-genome output: <-o>.fasta',default="output")
    return parser.parse_args()


def seqfileread(file):#readfa
    file = open(file,"r")
    lines = list(file.readlines())
    dic={}
    temp = ""
    for i in lines:
        if i.startswith(">"):
            temp = i.strip()[1:]
            dic[temp] = ""
            #print(temp)
        else:
            i = i.strip()
            dic[temp] = dic[temp] + i
    file.close()
    return dic

gosome = get_options()
seq1 = gosome.reference#sys.argv[1] #Firstgenome
seq2 = gosome.query#sys.argv[2] #Secondgenome

seqdic1 = seqfileread(seq1)
seqdic2 = seqfileread(seq2)


svfile = open(gosome.svguide,"r")#sys.argv[3]#svguidefile
svfileline = list(svfile.readlines())
svfile.close()
cumlength = 0

for i in svfileline:
    j = i.split()
    a = int(j[1]) + cumlength
    b = int(j[2]) + cumlength
    c = int(j[5])-1 + cumlength
    d = int(j[6])-1 + cumlength
    seqdic1[j[0]] = seqdic1[j[0]][:a] + seqdic2[j[4]][c:d+1] + seqdic1[j[0]][b:]
    cumlength += int(j[8])

outputfile = open(gosome.output+".fasta","w")    
for i in seqdic1.keys():
    print(">"+i,file = outputfile)
    print(seqdic1[i], file = outputfile)
    
outputfile.close()
    
    


    
